function  plot_bnds(headmodel, opts)
  figure('visible', opts.figure_windows);
  
  ft_plot_mesh(headmodel.bnd(1), ...
    'facecolor', [0.2 0.2 0.2],  ... 
    'facealpha', 0.3,            ...
    'edgecolor', [1 1 1],        ...
    'edgealpha', 0.05);
  % hold on;
  
  ft_plot_mesh(headmodel.bnd(2), ...
    'edgecolor', 'none',         ...
    'facealpha', 0.4);
  % hold on;
  
  ft_plot_mesh(headmodel.bnd(3), ...
    'edgecolor', 'none',         ...
    'facecolor', [0.4 0.6 0.4]);
  % hold on;
  
  print('output\bndplot', '-dpng', '-r300');
end